name: Build and Deploy Code

on: [push, pull_request]

env:
  DATABASE_HOSTNAME=localhost
  DATABASE_PORT=5432
  DATABASE_PASSWORD=DecemberJan1998!
  DATABASE_NAME=fastapi_test
  DATABASE_USERNAME=blaise
  SECRET_KEY=795ebf791baf37ad544f675f0a19e8b4eae49dc3bcd256660f8a3e60e82d5d1f
  ALGORITHM=HS256
  ACCESS_TOKEN_EXPIRE_MINUTES=30

jobs:
  job1:
    runs-on: ubuntu-latest
    # environment:
    #   name: testing
    

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: DecemberJan1998!
          POSTGRES_DB: fastapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest





# name: Build and Deploy Code

# on: [push,pull_request]

# jobs:
#   job1:
#     environment:
#       name: testing
#     env:
#       DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
#       DATABASE_PORT: ${{secrets.DATABASE_PORT}}
#       DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
#       DATABASE_NAME: ${{secrets.DATABASE_NAME}}
#       DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
#       SECRET_KEY: ${{secrets.SECRET_KEY}}
#       ALGORITHM: ${{secrets.ALGORITHM}}
#       ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
#           POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
#         ports:
#           - 5432:5432 
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#     runs-on: ubuntu-latest
#     steps:
#       - name: pulling git repo
#         uses: actions/checkout@v2
#       - name: Install Python version 3.8
#         uses: actions/setup-python@v3
#         with: 
#           python-version: "3.8"
#       - name: upgrade pip
#         run:  python -m pip install --upgrade pip
#       - name: install all dependencies
#         run:  pip install -r requirements.txt
#       - name: test with pytest
#         run:  |
#           pip install pytest
#           pytest
        
      